/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as FamilyImport } from './routes/_family'
import { Route as IndexImport } from './routes/index'
import { Route as FamilyFamilyImport } from './routes/_family.family'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const FamilyRoute = FamilyImport.update({
  id: '/_family',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FamilyFamilyRoute = FamilyFamilyImport.update({
  path: '/family',
  getParentRoute: () => FamilyRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_family': {
      preLoaderRoute: typeof FamilyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/_family/family': {
      preLoaderRoute: typeof FamilyFamilyImport
      parentRoute: typeof FamilyImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  FamilyRoute.addChildren([FamilyFamilyRoute]),
  AboutRoute,
])

/* prettier-ignore-end */
